name: Sync Fork

on:
  schedule:
    - cron: '0 1 * * *'  # 每天凌晨 1 点运行
  workflow_dispatch:     # 手动触发用的

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork repo
        uses: actions/checkout@v3
        with:
          ref: main  # 你默认分支名字是main就写main，master就写master

      - name: Set git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/mqiancheng/freecloud.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main --allow-unrelated-histories -m "Sync from upstream"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
